# This file was generated by GoReleaser. DO NOT EDIT.
class Pomdok < Formula
  desc "Simple wrapper to Symfony Go Binary for multi-app."
  homepage "https://github.com/Korbeil/pomdok"
  url "https://github.com/Korbeil/pomdok/releases/download/1.0.1/pomdok_1.0.1_Darwin_x86_64.tar.gz"
  version "1.0.1"
  sha256 "d3537a6a0ca0c79ca65fbbbdda75a407497830079025969dc0836cf320df8668"
  
  depends_on "wget"
  depends_on "nss"

  def install
    bin.install "pomdok"
  end
end
